
MACRO(generate_test_entry result_file entry)
	message(STATUS "it: ${entry}")

	get_filename_component(var_name ${entry} NAME_WE)

	STRING(CONFIGURE ${entry} entry ESCAPE_QUOTES)
	FILE(APPEND ${result_file} "const char ${var_name} [] = \"${entry}\";\n")

	message(STATUS "added file: ${entry} to testsuite with name: [${var_name}]")

ENDMACRO(generate_test_entry)



MACRO(generate_test_files_paths result_file data_dir)


	FILE(WRITE ${result_file} "#ifndef GENERATED_TEST_FILES_PATH_H\n")
	FILE(APPEND ${result_file} "#define GENERATED_TEST_FILES_PATH_H\n\n\n")
	FILE(APPEND ${result_file} "/* WARNING this file is automatically generated with CMake, do not edit */\n\n")


	FILE(GLOB fileList "${data_dir}/*.*")
	LIST(SORT fileList)

	foreach(it ${fileList})
		generate_test_entry(${result_file} ${it})
	endforeach()

	FILE(APPEND ${result_file} "\n\n#endif /* GENERATED_TEST_FILES_PATH_H */\n")

ENDMACRO(generate_test_files_paths)
